Repository jenkins-x/sso-operator, pull requests merged in 2019-04, with the labels that each got.

#25 chore: Ensure k8s resource names are not more than 63 chars
  pkg/proxy/expose.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: approved, lgtm, size/L

#26 chore: Add missing simple cases to proxy buildName function
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: approved, lgtm, size/M

#27 feat: initial commit of tekton pipeline
  Jenkinsfile
  charts/sso-operator/Makefile
  jenkins-x.yml
  skaffold.yaml
Labels: approved, size/L

#28 fix: updated release pipeline
  jenkins-x.yml
Labels: approved, size/XS

#29 fix: setting APP_NAME/ORG & DOCKER_REGISTRY variables
  jenkins-x.yml
Labels: approved, size/S

#30 fix: move chart dir to skip auto repo upgrade
  README.md
  charts/sso/preview/Chart.yaml
  charts/sso/preview/Makefile
  charts/sso/preview/requirements.yaml
  charts/sso/preview/values.yaml
  charts/sso/sso-operator/.helmignore
  charts/sso/sso-operator/Chart.yaml
  charts/sso/sso-operator/Makefile
  charts/sso/sso-operator/README.md
  charts/sso/sso-operator/templates/NOTES.txt
  charts/sso/sso-operator/templates/_helpers.tpl
  charts/sso/sso-operator/templates/cert-grpc-client.yaml
  charts/sso/sso-operator/templates/deployment.yaml
  charts/sso/sso-operator/templates/role.yaml
  charts/sso/sso-operator/templates/rolebinding.yaml
  charts/sso/sso-operator/templates/sa.yaml
  charts/sso/sso-operator/templates/service.yaml
  charts/sso/sso-operator/values.yaml
  jenkins-x.yml
Labels: approved, lgtm, size/XS
