Repository jenkins-x/sso-operator, pull requests merged in 2020-05, with the labels that each got.

#52 Helm chart: Allow changing the certificate issuer 'Kind' to support ClusterIssuers
  charts/sso-operator/templates/cert-grpc-client.yaml
  charts/sso-operator/values.yaml
Labels: approved, ok-to-test, size/XS

#55 fix: use of k8s API to read secret Data field
  pkg/operator/config.go
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#57 feat: update the go version in Dockerfile
  Dockerfile
Labels: size/XS
